// Code generated by templates/template.rb script. DO NOT EDIT.

package parser

type SyntaxWarningLevel int
type SyntaxWarningType int

const (
	SyntaxWarningDefault SyntaxWarningLevel = iota
	SyntaxWarningVerbose
)

const (
	WARN_AMBIGUOUS_FIRST_ARGUMENT_MINUS   SyntaxWarningType = 0
	WARN_AMBIGUOUS_FIRST_ARGUMENT_PLUS    SyntaxWarningType = 1
	WARN_AMBIGUOUS_PREFIX_AMPERSAND       SyntaxWarningType = 2
	WARN_AMBIGUOUS_PREFIX_STAR            SyntaxWarningType = 3
	WARN_AMBIGUOUS_PREFIX_STAR_STAR       SyntaxWarningType = 4
	WARN_AMBIGUOUS_SLASH                  SyntaxWarningType = 5
	WARN_COMPARISON_AFTER_COMPARISON      SyntaxWarningType = 6
	WARN_DOT_DOT_DOT_EOL                  SyntaxWarningType = 7
	WARN_EQUAL_IN_CONDITIONAL             SyntaxWarningType = 8
	WARN_EQUAL_IN_CONDITIONAL_3_3         SyntaxWarningType = 9
	WARN_END_IN_METHOD                    SyntaxWarningType = 10
	WARN_DUPLICATED_HASH_KEY              SyntaxWarningType = 11
	WARN_DUPLICATED_WHEN_CLAUSE           SyntaxWarningType = 12
	WARN_FLOAT_OUT_OF_RANGE               SyntaxWarningType = 13
	WARN_IGNORED_FROZEN_STRING_LITERAL    SyntaxWarningType = 14
	WARN_INTEGER_IN_FLIP_FLOP             SyntaxWarningType = 15
	WARN_INVALID_CHARACTER                SyntaxWarningType = 16
	WARN_INVALID_NUMBERED_REFERENCE       SyntaxWarningType = 17
	WARN_INVALID_SHAREABLE_CONSTANT_VALUE SyntaxWarningType = 18
	WARN_KEYWORD_EOL                      SyntaxWarningType = 19
	WARN_LITERAL_IN_CONDITION_DEFAULT     SyntaxWarningType = 20
	WARN_LITERAL_IN_CONDITION_VERBOSE     SyntaxWarningType = 21
	WARN_SHAREABLE_CONSTANT_VALUE_LINE    SyntaxWarningType = 22
	WARN_SHEBANG_CARRIAGE_RETURN          SyntaxWarningType = 23
	WARN_UNEXPECTED_CARRIAGE_RETURN       SyntaxWarningType = 24
	WARN_UNREACHABLE_STATEMENT            SyntaxWarningType = 25
	WARN_UNUSED_LOCAL_VARIABLE            SyntaxWarningType = 26
	WARN_VOID_STATEMENT                   SyntaxWarningType = 27
)

var SyntaxWarningLevels = []SyntaxWarningLevel{SyntaxWarningDefault, SyntaxWarningVerbose}
var SyntaxWarningTypes = []SyntaxWarningType{
	WARN_AMBIGUOUS_FIRST_ARGUMENT_MINUS,
	WARN_AMBIGUOUS_FIRST_ARGUMENT_PLUS,
	WARN_AMBIGUOUS_PREFIX_AMPERSAND,
	WARN_AMBIGUOUS_PREFIX_STAR,
	WARN_AMBIGUOUS_PREFIX_STAR_STAR,
	WARN_AMBIGUOUS_SLASH,
	WARN_COMPARISON_AFTER_COMPARISON,
	WARN_DOT_DOT_DOT_EOL,
	WARN_EQUAL_IN_CONDITIONAL,
	WARN_EQUAL_IN_CONDITIONAL_3_3,
	WARN_END_IN_METHOD,
	WARN_DUPLICATED_HASH_KEY,
	WARN_DUPLICATED_WHEN_CLAUSE,
	WARN_FLOAT_OUT_OF_RANGE,
	WARN_IGNORED_FROZEN_STRING_LITERAL,
	WARN_INTEGER_IN_FLIP_FLOP,
	WARN_INVALID_CHARACTER,
	WARN_INVALID_NUMBERED_REFERENCE,
	WARN_INVALID_SHAREABLE_CONSTANT_VALUE,
	WARN_KEYWORD_EOL,
	WARN_LITERAL_IN_CONDITION_DEFAULT,
	WARN_LITERAL_IN_CONDITION_VERBOSE,
	WARN_SHAREABLE_CONSTANT_VALUE_LINE,
	WARN_SHEBANG_CARRIAGE_RETURN,
	WARN_UNEXPECTED_CARRIAGE_RETURN,
	WARN_UNREACHABLE_STATEMENT,
	WARN_UNUSED_LOCAL_VARIABLE,
	WARN_VOID_STATEMENT,
}

type SyntaxWarning struct {
	Message  string
	Location *Location
	Level    SyntaxWarningLevel
	Type     SyntaxWarningType
}

func NewSyntaxWarning(
	message string,
	location *Location,
	level SyntaxWarningLevel,
	warnType SyntaxWarningType,
) *SyntaxWarning {
	return &SyntaxWarning{
		Message:  message,
		Location: location,
		Level:    level,
		Type:     warnType,
	}
}
